command:
- ${env}
- ${interpreter}
- ${program}
- "--config"
- "config.yaml"
- ${args}

program: main.py
entity: yuval_eyal
project: nl2bash

method: grid
parameters:
  val_batch:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  example_batch:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]