command:
- ${env}
- ${interpreter}
- ${program}
- "--config"
- "config.yaml"
- ${args}

program: main.py
entity: yuval_eyal
project: nl2bash

method: grid
parameters:
 prompt_method:
  values: [1, 2, 3, 4]
        
    